package main

import (
	"bytes"
	"go/format"
	"text/template"
)

// outputTemplate is the Go source template for the generated file.
// It is intentionally kept simple: one package declaration, the needed import
// block, and a single variable holding the ordered slice of model pointers.
const outputTemplate = `// Code generated by gormtables; DO NOT EDIT.

package {{.PkgName}}

{{- if .Imports}}

import (
{{- range $alias, $path := .Imports}}
	{{$alias}} "{{$path}}"
{{- end}}
)
{{- end}}

// {{.VarName}} is the ordered list of GORM models for AutoMigrate.
// Tables that are depended upon by others appear later in the slice so that
// foreign-key constraints can be satisfied during migration.
var {{.VarName}} = []any{
{{- range .Models}}
{{- if .PkgAlias}}
	&{{.PkgAlias}}.{{.TypeName}}{},
{{- else}}
	&{{.TypeName}}{},
{{- end}}
{{- end}}
}
`

// templateData is the data passed to outputTemplate.
type templateData struct {
	PkgName string
	Imports map[string]string
	VarName string
	Models  []modelEntry
}

// renderOutput executes the template against data and returns gofmt-formatted
// Go source bytes.
func renderOutput(data templateData) ([]byte, error) {
	tmpl, err := template.New("output").Parse(outputTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	return format.Source(buf.Bytes())
}
