package main

import (
	"go/format"
	"strings"
	"testing"
)

// TestRenderOutputCrossPackage verifies that renderOutput generates valid,
// gofmt-formatted Go source with the correct import statement when the models
// live in a different package from the output file.
func TestRenderOutputCrossPackage(t *testing.T) {
	data := templateData{
		PkgName: "database",
		Imports: map[string]string{
			"model": "example.com/app/internal/model",
		},
		VarName: "autoMigrateTables",
		Models: []modelEntry{
			{PkgAlias: "model", TypeName: "User"},
			{PkgAlias: "model", TypeName: "Post"},
		},
	}

	src, err := renderOutput(data)
	if err != nil {
		t.Fatalf("renderOutput: %v", err)
	}

	out := string(src)
	if !strings.Contains(out, `package database`) {
		t.Errorf("missing package declaration:\n%s", out)
	}
	if !strings.Contains(out, `example.com/app/internal/model`) {
		t.Errorf("missing import path:\n%s", out)
	}
	if !strings.Contains(out, `&model.User{}`) {
		t.Errorf("missing model reference:\n%s", out)
	}
	if !strings.Contains(out, `// Code generated by gormtables`) {
		t.Errorf("missing code-generated header:\n%s", out)
	}
}

// TestRenderOutputSamePackage verifies that when models are in the same package
// as the output file, references are emitted without a package qualifier.
func TestRenderOutputSamePackage(t *testing.T) {
	data := templateData{
		PkgName: "model",
		Imports: map[string]string{}, // same package → no imports
		VarName: "tables",
		Models: []modelEntry{
			{PkgAlias: "", TypeName: "User"},
		},
	}

	src, err := renderOutput(data)
	if err != nil {
		t.Fatalf("renderOutput: %v", err)
	}

	out := string(src)
	if !strings.Contains(out, `&User{}`) {
		t.Errorf("expected unqualified reference &User{}, got:\n%s", out)
	}
	if strings.Contains(out, "model.User") {
		t.Errorf("unexpected qualified reference in same-package output:\n%s", out)
	}
}

// TestRenderOutputGoFmtStable verifies that the output is already gofmt-clean:
// passing it through format.Source a second time should yield identical bytes.
func TestRenderOutputGoFmtStable(t *testing.T) {
	data := templateData{
		PkgName: "db",
		Imports: map[string]string{"m": "example.com/m"},
		VarName: "Tables",
		Models:  []modelEntry{{PkgAlias: "m", TypeName: "Foo"}},
	}

	src1, err := renderOutput(data)
	if err != nil {
		t.Fatalf("renderOutput: %v", err)
	}

	src2, err := format.Source(src1)
	if err != nil {
		t.Fatalf("format.Source on generated output: %v", err)
	}

	if string(src1) != string(src2) {
		t.Errorf("output is not gofmt-stable:\nfirst:\n%s\nsecond:\n%s", src1, src2)
	}
}
