// Code generated by gormtables; DO NOT EDIT.

package database

import (
	models "github.com/hr3lxphr6j/gormtables/testdata/models"
)

// autoMigrateTables is the ordered list of GORM models for AutoMigrate.
// Tables that are depended upon by others appear later in the slice so that
// foreign-key constraints can be satisfied during migration.
var autoMigrateTables = []any{
	&models.Post{},
	&models.Tag{},
	&models.User{},
}
